# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # ═══════════════════════════════════════════════
  # JOB 1: Validación de Código
  # ═══════════════════════════════════════════════
  quality:
    name:  Calidad de Código
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Instalar dependencias
      run: make install
    
    - name: Ejecutar Linting
      run: make lint
      continue-on-error: true
    
    - name: Auditoría de Seguridad
      run: make security
      continue-on-error: true

  # ═══════════════════════════════════════════════
  # JOB 2: Tests
  # ═══════════════════════════════════════════════
  test:
    name:  Tests Automatizados
    runs-on: ubuntu-latest
    needs: quality
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Instalar dependencias
      run: make install
    
    - name: Ejecutar tests
      run: make test
    
    - name: Subir reporte de cobertura
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/

  # ═══════════════════════════════════════════════
  # JOB 3: Empaquetar
  # ═══════════════════════════════════════════════
  package:
    name:  Empaquetar Lambda
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Crear paquete
      run: make package
    
    - name: Subir artefacto
      uses: actions/upload-artifact@v3
      with:
        name: lambda-package
        path: lambda.zip

  # ═══════════════════════════════════════════════
  # JOB 4: Desplegar a AWS
  # ═══════════════════════════════════════════════
  deploy:
    name:  Desplegar a AWS
    runs-on: ubuntu-latest
    needs: package
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Descargar paquete
      uses: actions/download-artifact@v3
      with:
        name: lambda-package
    
    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Desplegar Lambda
      run: |
        aws lambda update-function-code \
          --function-name fastapi-tasks-api \
          --zip-file fileb://lambda.zip
    
    - name:  Despliegue completado
      run: echo "Despliegue exitoso en AWS Lambda"
